package the_fireplace.hvii.config;
/**
 * @author The_Fireplace
 */
public class ConfigValues {
	public static final boolean ENABLECAPETOGGLE_DEFAULT = false;
	public static boolean ENABLECAPETOGGLE;
	public static final String ENABLECAPETOGGLE_NAME = "cape_toggle";
	public static final boolean ENABLEJACKETTOGGLE_DEFAULT = true;
	public static boolean ENABLEJACKETTOGGLE;
	public static final String ENABLEJACKETTOGGLE_NAME = "jacket_toggle";
	public static final boolean ENABLELEFTSLEEVETOGGLE_DEFAULT = true;
	public static boolean ENABLELEFTSLEEVETOGGLE;
	public static final String ENABLELEFTSLEEVETOGGLE_NAME = "left_sleeve_toggle";
	public static final boolean ENABLERIGHTSLEEVETOGGLE_DEFAULT = true;
	public static boolean ENABLERIGHTSLEEVETOGGLE;
	public static final String ENABLERIGHTSLEEVETOGGLE_NAME = "right_sleeve_toggle";
	public static final boolean ENABLELEFTPANTSLEGTOGGLE_DEFAULT = true;
	public static boolean ENABLELEFTPANTSLEGTOGGLE;
	public static final String ENABLELEFTPANTSLEGTOGGLE_NAME = "left_pants_leg_toggle";
	public static final boolean ENABLERIGHTPANTSLEGTOGGLE_DEFAULT = true;
	public static boolean ENABLERIGHTPANTSLEGTOGGLE;
	public static final String ENABLERIGHTPANTSLEGTOGGLE_NAME = "right_pants_leg_toggle";
	public static final boolean ENABLEHATTOGGLE_DEFAULT = true;
	public static boolean ENABLEHATTOGGLE;
	public static final String ENABLEHATTOGGLE_NAME = "hat_toggle";
	public static final int NORMALBRIGHTNESS_DEFAULT = 1;
	public static int NORMALBRIGHTNESS;
	public static final String NORMALBRIGHTNESS_NAME = "normal_brightness";
	public static final String[] GLOWINGENTITIES_DEFAULT = new String[]{"EntityPlayerMP"};
	public static String[] GLOWINGENTITIES;
	public static final String GLOWINGENTITIES_NAME = "glowingentities";
	public static final String[] EXCLUDEORES_DEFAULT = new String[]{"oreCoal"};
	public static String[] EXCLUDEORES;
	public static final String EXCLUDEORES_NAME = "excludeores";
	public static final int TPU_DEFAULT = 10;
	public static int TPU;
	public static final String TPU_NAME = "tpu";
	public static final int ATD_DEFAULT = 500;
	public static int ATD;
	public static final String ATD_NAME = "atd";
	public static final String PATS_PARTICLE1_DEFAULT = "flame";
	public static String PATS_PARTICLE1;
	public static final String PATS_PARTICLE1_NAME = "pats_particle_primary";
	public static final String PATS_PARTICLE2_DEFAULT = "smoke_normal";
	public static String PATS_PARTICLE2;
	public static final String PATS_PARTICLE2_NAME = "pats_particle_secondary";
	public static final boolean ENABLE_PATS_PRIMARY_DEFAULT = true;
	public static boolean ENABLE_PATS_PRIMARY;
	public static String ENABLE_PATS_PRIMARY_NAME = "enable_pats_primary";
	public static final boolean ENABLE_PATS_SECONDARY_DEFAULT = true;
	public static boolean ENABLE_PATS_SECONDARY;
	public static String ENABLE_PATS_SECONDARY_NAME = "enable_pats_secondary";
	public static final boolean EXTENSIVE_PATS_SECONDARY_DEFAULT = true;
	public static boolean EXTENSIVE_PATS_SECONDARY;
	public static String EXTENSIVE_PATS_SECONDARY_NAME = "extensive_pats_secondary";
	public static final String PATS_KEY_BEHAVIOR_DEFAULT = "toggle";
	public static String PATS_KEY_BEHAVIOR;
	public static final String PATS_KEY_BEHAVIOR_NAME = "pats_thrown_key_behavior";
	public static final boolean ENABLETARGETLINES_DEFAULT = true;
	public static boolean ENABLETARGETLINES;
	public static final String ENABLETARGETLINES_NAME = "enable_target_lines";
}
